services:
  - type: web
    name: pdftothermal
    runtime: node
    region: ohio
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
